apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: ecommerce
spec:
  headers:
    accessControlAllowOriginList:
      - "http://ecommerce.local:30080"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "PUT"
      - "DELETE"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    accessControlAllowCredentials: true
    addVaryHeader: true